import re,json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
s=(root/'references/live-styles.css').read_text()
colors={name:{'value':value.upper() if value.startswith('#') else value,'evidence':'live-css','sourceVariable':'--'+name} for name,value in re.findall(r'--([\w-]+):\s*(#[\da-fA-F]{6}|rgba\([^)]+\))\s*;',s)}
for name,value in re.findall(r'--([\w-]+):\s*(color\(display-p3 [^)]+\))\s*;',s):
 if name in colors:colors[name]['displayP3']=value
result={'meta':{'name':'Family · extracted design system','date':'2026-09-06','reference':'https://recent.design/i/p1lu7hn-family','live':'https://family.co/','note':'Color names/hex/P3 are original CSS. Other token names are normalized extraction. Video is an older version; do not treat current values as exact historical values.'},'color':colors,'typography':{'display':{'family':'Family','weight':500,'size':'68px','lineHeight':'1.1','letterSpacing':'-0.02em','mobile':{'maxWidth':'580px','size':'44px','lineHeight':'48px','letterSpacing':'-1.35px'},'evidence':'live-css'},'heading':{'family':'Family','weight':500,'size':'44px','lineHeight':'48px','letterSpacing':'-1.35px','mobile':{'maxWidth':'420px','size':'32px','lineHeight':'35px','letterSpacing':'-0.69px'},'evidence':'live-css'},'body':{'family':'Inter','weight':400,'size':'16px','evidence':'live-computed'},'button':{'family':'Inter','weight':500,'size':'15px','letterSpacing':'-0.09px','evidence':'live-computed'}},'layout':{'contentMax':{'value':'1024px','evidence':'live-computed'},'gutter':{'value':'24px','evidence':'live-computed'},'breakpoints':{'value':[390,410,420,580,720,768,880,920],'evidence':'live-css','note':'Component-specific; not a universal breakpoint scale.'}},'radius':{str(v):{'value':str(v)+'px','evidence':'live-computed'} for v in [6,8,10,12,32,40,72]},'motion':{'nav':{'duration':'200ms','properties':['background','color'],'evidence':'live-css'},'dropdown':{'duration':'100ms','properties':['opacity','transform'],'evidence':'live-css'},'responsiveTransform':{'duration':'220ms','easing':'cubic-bezier(0.19,1,0.22,1)','evidence':'live-css'},'longTransform':{'duration':'1000ms','easing':'cubic-bezier(0.19,1,0.22,1)','evidence':'live-css'},'testimonialRail':{'target':'Testimonials__RowContainer / .Qwkbu','duration':'120s','easing':'linear','iteration':'infinite','evidence':'live-css'}},'recommended':{'focusRing':{'value':'2px solid #343433','evidence':'recommended'},'touchTarget':{'value':'44px','evidence':'recommended'},'reducedMotion':{'value':'Stop looping/decorative animation; show final state; video user-play only.','evidence':'recommended'}}}
# Normalize reusable roles while preserving which names are our interpretation.
for name,size,line,tracking,weights in [('bodyLarge',19,27,-.3,[400,500]),('bodyLead',17,26,-.22,[400,500]),('bodySmall',15,22,-.13,[400,500]),('caption',14,20,-.09,[400,600]),('captionSmall',13,18,-.13,[400,500]),('micro',12,19,-.01,[400]),('componentTitle',23,25,-.44,[500])]:
 result['typography'][name]={'family':'Inter','weights':weights,'size':f'{size}px','lineHeight':f'{line}px','letterSpacing':f'{tracking}px','evidence':'live-css','note':'Role name normalized; values extracted.'}
result['layout'].update({'wrapperMax':{'value':'67rem','evidence':'live-css','selector':'.hKlZHw'},'splitGap':{'value':'5.75rem','evidence':'live-css'},'bentoGap':{'value':'34px','evidence':'live-css'},'phoneGridGap':{'value':'2rem','mobileValue':'1.5rem','evidence':'live-css'},'articleGap':{'value':'1.75rem','evidence':'live-css'}})
result['shadow']={'dropdown':{'value':'0 3px 16px rgba(0,0,0,.1)','evidence':'live-css'},'soft':{'value':'0 0 24px rgba(0,0,0,.15)','evidence':'live-computed'}}
result['motion'].update({'button':{'duration':'100ms','easing':'ease','properties':['background-color'],'evidence':'live-css'},'imageHover':{'duration':'180ms','easing':'ease','from':'scale(1)','to':'scale(1.02)','evidence':'live-css','selector':'.kordEf'},'skeleton':{'duration':'1200ms','easing':'linear','iteration':'infinite','from':'background-position:100%','to':'background-position:-100%','evidence':'live-css'},'faqEstimate':{'durationRangeMs':[250,300],'evidence':'video-estimate','easing':None,'note':'Approximate expansion; exact JS timing/easing unavailable.'},'heroEstimate':{'durationRangeMs':[600,1000],'evidence':'video-estimate','loopDuration':None}})
result['components']={'button':{'height':'48px','compactHeight':'32px','radius':'32px','background':'#171717','lightBackground':'#F6F4EF','evidence':'live-css'},'dropdown':{'width':'316px','maxWidth':'calc(100vw - 18px)','padding':'4px','radius':'8px','offset':'5px','closedTransform':'scale(.96)','evidence':'live-css'}}
result['meta']['motionSourceOfTruth']='motion-source-tokens.json'
result['meta']['version']=2
for key in ['faqEstimate','heroEstimate']:
 result['motion'][key]['supersededBy']='motion-source-tokens.json (current bundle values); this entry preserves old video observation only.'
(root/'tokens.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
css='/* Extracted from family.co, 2026-09-06. Original names and fallbacks preserved. */\n:root {\n'+''.join(f'  --{k}: {v["value"]};\n' for k,v in colors.items())+'}\n@supports (color: color(display-p3 1 1 1)) {\n  :root {\n'+''.join(f'    --{k}: {v["displayP3"]};\n' for k,v in colors.items() if 'displayP3' in v)+'  }\n}\n/* Normalized extraction aliases; names are not original source tokens. */\n:root {\n  --family-font-display: "Family", Arial, sans-serif;\n  --family-font-body: "Inter", Arial, sans-serif;\n  --family-content-max: 1024px;\n  --family-gutter: 24px;\n  --family-duration-nav: 200ms;\n  --family-duration-dropdown: 100ms;\n  --family-duration-transform: 220ms;\n  --family-ease-out: cubic-bezier(.19,1,.22,1);\n}\n'
(root/'tokens.css').write_text(css)
print(f'Extracted {len(colors)} original color variables')
