"""Generate whole-page and opt-in scoped tokens from tokens.json (the canonical values)."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
DS = ROOT / 'design-system'
data = json.loads((DS / 'tokens.json').read_text())
values = {}
for group in ['color', 'font', 'space']:
    for key, token in data[group].items():
        values[f'--{group}-{key}'] = str(token['value'])
for name, token in data['typography'].items():
    for prop, prefix in [('fontSize','font-size'),('lineHeight','line-height'),('letterSpacing','tracking')]:
        if prop in token['value']:
            values[f'--{prefix}-{name}'] = str(token['value'][prop])
for name, token in data['size'].items():
    values[f'--{name}'] = str(token['value'])
for name, token in data['radius'].items():
    values[f'--radius-{name}'] = str(token['value'])
for name, variable in [('default','border-width'),('focus','focus-ring-width'),('focus-offset','focus-ring-offset')]:
    values[f'--{variable}'] = str(data['border'][name]['value'])
for name, token in data['motion'].items():
    values[f'--duration-{name}'] = str(token['value'])
light = {name:value for name,value in values.items() if name.startswith('--color-')}
dark = {f'--color-{name}':str(token['value']) for name,token in data['dark'].items()}
def rule(selector, declarations):
    return selector + ' {\n' + ''.join(f'  {key}: {value};\n' for key,value in declarations.items()) + '}\n'
header = '/* Generated by scripts/build-tokens.py from tokens.json. Edit JSON, then rebuild. */\n'
for scoped in [False, True]:
    owner = '.adver-system' if scoped else ':root'
    theme = lambda name: f'.adver-system[data-theme="{name}"], .adver-system [data-theme="{name}"]' if scoped else f'[data-theme="{name}"]'
    css = header + rule(owner,values) + '\n' + rule(theme('light'),light) + '\n' + rule(theme('dark'),dark)
    css += '\n@media (prefers-color-scheme: dark) {\n' + rule(theme('system'),dark) + '}\n'
    css += '\n@media (prefers-reduced-motion: reduce) {\n' + rule(owner,{'--duration-fast':'0ms','--duration-standard':'0ms'}) + '}\n'
    filename = 'tokens.scoped.css' if scoped else 'tokens.css'
    (DS / filename).write_text(css)
print(f'Generated global/scoped tokens from {len(values)} canonical variables.')
