(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const source = window.ARK_SOURCE || {document: {}, stats: {}, pages: [], images: [], graphics: [], fonts: []};
  const system = window.ARK_SYSTEM || {templates: [], recipes: []};
  const foundation = window.ARK_FOUNDATION || {colors: []};
  const escapeHTML = (value) => String(value ?? '').replace(/[&<>"']/g, (ch) => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[ch]));
  const pathURL = (path) => encodeURI(String(path)).replace(/#/g, '%23').replace(/\?/g, '%3F');
  const routes = {overview: '시스템 개요', foundation: '디자인 원칙', assets: '소스 라이브러리', layouts: '문서 템플릿', components: '컴포넌트', prompts: '프롬프트 스튜디오', source: 'PDF 원본 탐색', downloads: '다운로드'};
  const pageNames = {cover:'표지', divider:'장 구분', contents:'목차', brand:'브랜드', data:'데이터 · 표', product:'제품 · 서비스', project:'프로젝트', photo:'사진', process:'프로세스', partners:'파트너', contact:'연락처'};
  let activeRoute = 'overview';
  let assetFilter = 'all';
  let assetLimit = 32;
  let toastTimer;
  let lastDialogTrigger;
  const pageRefs = (pages = []) => pages.map(n => `p.${n}`).join(' · ');
  const families = {
    outline:{name:'선형 아이콘', english:'OUTLINE UTILITY', pages:[15,26], graphic:'p26-icon-accommodations', description:'명확한 외곽선과 열린 내부 공간. 원본의 블루 그라데이션과 인쇄용 단색을 구분합니다.', tags:['48 × 48', '3 UNIT STROKE', 'ROUND CAP', '4 UNIT SAFE AREA'], rules:'48×48 viewBox. 주 선 두께 3 units, round cap과 round join. 사방 최소 4 units 여백. 채움 없이 외곽선 중심으로 2–4개의 내부 단서만 남긴다. 광학적으로 중앙 정렬한다.', englishRules:'48×48 viewBox; 3-unit consistent stroke, round caps and joins, no fill, minimum 4-unit safe area. Use 2–4 meaningful internal cues. Center the optical mass.', negative:'사진 질감, 금속 광택, 입체 돌출, 그림자, 반짝임, 금색 재질, 캐릭터, 불규칙한 선 굵기, 작은 글씨 금지.', englishNegative:'No photography, metallic shine, 3D extrusion, shadows, sparkles, gold material, mascot styling, inconsistent strokes or tiny text.'},
    solid:{name:'면형 품질 심볼',english:'FILLED QUALITY',pages:[29],graphic:'p29-icon-accountability',description:'품질·인증·책임을 표현하는 묵직한 실루엣. 선형 아이콘보다 더 단순한 형태로 만듭니다.',tags:['48 × 48', 'FILLED SILHOUETTE', 'OPEN COUNTERS'],rules:'48×48 viewBox. 단순한 채움 실루엣과 넓은 음각 공간. 정밀·준수·책임을 나타내는 1–2개의 기호만 사용. 선형 계열과 같은 행에서 혼합하지 않는다.',englishRules:'48×48 viewBox; compact filled silhouettes with generous negative space. Use 1–2 symbols for precision, compliance or accountability. Keep this family separate from outline icon rows.',negative:'캐릭터 표정, 사진, 세밀한 질감, 복잡한 다색 로고, 지나치게 얇은 선 금지.',englishNegative:'No mascot expressions, photography, detailed textures, multicolor logos or fragile outlines.'},
    mascot:{name:'부서 캐릭터',english:'MASCOT ILLUSTRATION',pages:[9],graphic:'p09-character-sales',description:'옐로 캐릭터와 네이비 헬멧. 동작과 소품을 바꾸되 인물의 형태와 표정은 유지합니다.',tags:['YELLOW BODY', 'NAVY HELMET', 'SAME CHARACTER'],rules:'원본 p9의 캐릭터 비율, 노란 몸체, 네이비 헬멧, 짙은 외곽선과 흰 얼굴을 유지한다. 주제는 포즈와 한 가지 소품으로 변경한다. 새 로고나 불필요한 문자를 만들지 않는다.',englishRules:'Preserve the p9 character proportions, yellow body, navy helmet, dark outline and white face. Change only the pose and one relevant prop. Do not invent a new logo or unnecessary text.',negative:'사실적인 사람, 다른 캐릭터 종, 기존 캐릭터 재설계, 아이콘 그리드에 혼합, 3D 피규어 금지.',englishNegative:'No realistic humans, different species, character redesign, mixed icon grids or 3D figurines.'},
    wireframe:{name:'건축 와이어프레임',english:'ARCHITECTURAL WIREFRAME',pages:[5],graphic:'p05-prefab-building',description:'짙은 배경 위 정밀한 선과 반복 구조. 모듈러 구조와 기술적인 공간을 설명합니다.',tags:['16:9', 'THIN LINE', 'MODULAR RHYTHM'],rules:'1920×1080, 짙은 네이비 #061A58 배경. 얇은 스틸/화이트 선, 일정한 모듈 반복, 평행한 구조선과 일관된 축측 시점. 제목을 위한 왼쪽 상단 여백을 남긴다. 같은 출력 크기에서 선의 밀도를 유지한다.',englishRules:'1920×1080 canvas, deep navy #061A58 background. Thin steel/white lines, repeated modules, parallel structural edges and a consistent axonometric viewpoint. Leave top-left title space; preserve line density at the intended output size.',negative:'사진 렌더링, 복잡한 실내 장식, 유기적 곡선, 광원 과장, 무관한 노란 강조 금지.',englishNegative:'No photorealistic render, interior clutter, organic curves, dramatic lighting or unrelated yellow highlights.'},
    volume:{name:'볼륨 데이터 도형',english:'SOFT VOLUMETRIC DATA',pages:[14],graphic:null,description:'부드러운 블루 볼륨은 비율과 규모의 표현에 한정합니다. 수치의 비교 기준은 별도로 명시합니다.',tags:['BLUE VOLUME', 'LABELED VALUES', 'HONEST SCALE'],rules:'p14처럼 부드러운 블루/인디고 볼륨을 사용한다. 모든 값에 단위와 기준일을 붙인다. 크기가 데이터에 비례하면 면적 또는 부피 기준을 명시하고 정확히 계산한다. 그렇지 않으면 개념도·축척 없음으로 표시한다. 수치를 새로 만들어 사실처럼 제시하지 않는다.',englishRules:'Use soft blue/indigo volumes as in p14. Label every value, unit and reference date. If size encodes data, state and calculate the area or volume scale accurately; otherwise label the graphic conceptual and not to scale. Never invent factual data.',negative:'금속 재질, 무지개 색, 범례 없는 크기 차이, 왜곡된 통계, 근거 없는 숫자 금지.',englishNegative:'No metallic materials, rainbow palette, unexplained size differences, distorted statistics or invented facts.'},
    layout:{name:'문서 레이아웃',english:'DOCUMENT COMPOSITION',pages:[3,4,19,31,46],graphic:null,description:'16:9 정보 구조, 일관된 여백과 페이지 레일. 내용에 맞는 템플릿을 선택합니다.',tags:['1920 × 1080', '48–60 MARGIN', 'ONE MESSAGE'],rules:'1920×1080 16:9. 바깥 여백 48–60 source units, 하단 얇은 레일. 본문 배경 #F4F4F8, 제목 #1A2646. 장 구분은 #011187 배경과 큰 흰 장 번호. 제목 85, 본문 최소24–25 source units를 기본으로 비례 조정. 한 페이지에 핵심 메시지 하나. 모든 텍스트와 표를 편집 가능하게 만든다.',englishRules:'1920×1080 16:9; 48–60 source-unit outer margin and thin footer rail. Paper #F4F4F8, ink #1A2646; dividers use #011187 with a large white numeral. Use title size 85 and body size at least 24–25 source units, scaled proportionally. One primary message per page; keep text and tables editable.',negative:'무의미한 카드, 과한 라운드, 텍스트 이미지화, 불필요한 장식, 출처 없는 통계 금지.',englishNegative:'No arbitrary cards, excessive rounding, rasterized text, unnecessary decoration or unsourced statistics.'}
  };
  function notify(message) { $('toast').textContent=message; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000); }
  async function copyText(text, fallback) {
    try { if(!navigator.clipboard) throw new Error('Clipboard unavailable'); await navigator.clipboard.writeText(text); notify('클립보드에 복사했습니다.'); }
    catch { const input=document.createElement('textarea'); input.value=text; input.style.position='fixed'; input.style.opacity='0'; document.body.append(input); input.select(); const ok=document.execCommand('copy'); input.remove(); if(ok) notify('클립보드에 복사했습니다.'); else { if(fallback){fallback.focus();fallback.select();} notify('자동 복사가 제한되어 있습니다. 텍스트를 선택해 복사하세요.'); } }
  }
  function downloadText(text, filename, mime='text/plain;charset=utf-8') {const url=URL.createObjectURL(new Blob([text],{type:mime}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify(`${filename} 다운로드를 시작했습니다.`);}
  function changeRoute() {
    const requested=location.hash.slice(1).split('?')[0]; const route=Object.hasOwn(routes,requested)?requested:'overview';
    document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==`panel-${route}`);
    document.querySelectorAll('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===route); if(a.dataset.route===route) a.setAttribute('aria-current','page'); else a.removeAttribute('aria-current');});
    $('breadcrumb-current').textContent=routes[route];document.title=`${routes[route]} — ARK Document System`;
    if(activeRoute!==route){window.scrollTo({top:0,behavior:'instant'});$('main').focus({preventScroll:true});} activeRoute=route;
  }
  const graphicById = id => source.graphics.find(g=>g.id===id);
  const assetList=[...source.graphics.map(g=>({...g,assetType:'graphics',displayType:'graphic',label:g.name,pages:[g.page],origin:'source',download:g.path})),...system.recipes.map(r=>({...r,assetType:'icons',displayType:'icon',label:r.name,preview:r.gradientPath||r.path,pages:r.sourcePages,origin:'extension',download:r.gradientPath||r.path})),...source.images.map((im,i)=>({...im,assetType:'images',displayType:'image',cardPreview:im.thumbnail||im.preview,label:`${pageNames[source.pages.find(p=>p.number===im.pages[0])?.category]||'원본'} 이미지 ${String(i+1).padStart(2,'0')}`,origin:'source',download:im.path}))];
  function renderStats() { $('nav-assets').textContent=assetList.length; $('stat-images').innerHTML=`${source.stats.images||0}<span>images</span>`; $('stat-graphics').innerHTML=`${source.stats.graphics||0}<span>graphics</span>`; $('stat-templates').innerHTML=`${system.templates.filter(t=>t.category==='slide').length}<span>layouts</span>`; }
  function renderColors() { $('color-grid').innerHTML=foundation.colors.map(c=>`<button class="color-card" data-color="${c.hex}" aria-label="${c.id} ${c.hex} 복사"><span class="color-fill" style="background:${c.hex};color:${['white','paper','yellow','rule'].includes(c.id)?'#091955':'white'}"></span><span class="color-meta"><strong>${escapeHTML(c.id)}</strong><code>${c.hex}</code><small>${escapeHTML(c.role)}</small><span class="badge ${c.origin==='observed'?'source':'new'}">${c.origin==='observed'?`관찰값 · ${pageRefs(c.sourcePages)}`:'웹 적용 제안'}</span></span></button>`).join(''); document.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>copyText(b.dataset.color))); document.querySelector('.grid-columns').innerHTML='<i></i>'.repeat(12); }
  function renderFamilies() { $('family-cards').innerHTML=Object.entries(families).filter(([id])=>id!=='layout').map(([id,f])=>{const g=graphicById(f.graphic);const preview=g?.preview||`source/previews/page-${String(f.pages[0]).padStart(3,'0')}.jpg`;return `<article class="family-card"><div class="family-image"><img src="${pathURL(preview)}" alt="${f.name} 원본 참고" loading="lazy"></div><div class="family-text"><span class="eyebrow">${f.english}</span><h3>${f.name}</h3><p>${f.description}</p><span class="source-ref">${pageRefs(f.pages)}</span><button class="link-button" data-use-family="${id}">이 계열로 확장 ↗</button></div></article>`;}).join(''); }
  function renderAssets() {
    const q=$('asset-search').value.trim().toLocaleLowerCase(); const filtered=assetList.filter(a=>(assetFilter==='all'||assetFilter===a.assetType)&&[a.label,a.id,a.category,a.description,a.subject,a.pages.join(' '),a.assetType].join(' ').toLocaleLowerCase().includes(q));
    $('asset-result-count').textContent=`${filtered.length}개의 소스 / 전체 ${assetList.length}개`;
    $('asset-grid').innerHTML=filtered.slice(0,assetLimit).map(a=>`<button class="asset-card ${a.displayType}" data-asset-id="${escapeHTML(a.id)}" aria-label="${escapeHTML(a.label)} 상세 보기"><span class="asset-preview"><img src="${pathURL(a.cardPreview||a.preview)}" alt="${escapeHTML(a.label)}" loading="lazy" decoding="async"></span><span class="asset-info"><h3>${escapeHTML(a.label)}</h3><div><span class="badge ${a.origin==='extension'?'new':'source'}">${a.origin==='extension'?'확장 예시':'원본 추출'}</span><code>${a.pages.length>3?`${pageRefs(a.pages.slice(0,2))} +${a.pages.length-2}`:pageRefs(a.pages)}</code></div></span></button>`).join('');
    $('asset-more').hidden=filtered.length<=assetLimit; $('asset-empty').hidden=filtered.length>0;
  }
  function downloadLink(path,label){return `<a class="button secondary" href="${pathURL(path)}" download>${escapeHTML(label)} ↓</a>`;}
  function showDialog({title,kind,image,description,links,isIcon=false},trigger) {lastDialogTrigger=trigger||document.activeElement;$('dialog-title').textContent=title;$('dialog-kind').textContent=kind;$('dialog-image').src=pathURL(image);$('dialog-image').alt=title;$('dialog-image').parentElement.classList.toggle('icon',isIcon);$('dialog-description').textContent=description;$('dialog-links').innerHTML=links;$('asset-dialog').showModal();$('dialog-close').focus();}
  function showAsset(id,trigger) {const a=assetList.find(x=>x.id===id);if(!a)return;let details=`${pageRefs(a.pages)} · ${a.origin==='extension'?'관찰한 규칙으로 새로 만든 확장 예시':'PDF에서 추출한 원본 소스'}`;let links=downloadLink(a.download,a.origin==='extension'?'원본 톤 SVG':a.assetType==='graphics'?'원본 SVG':'원본 형식');if(a.assetType==='images'){details+=`\n${a.width} × ${a.height} px · ${a.path.split('.').pop().toUpperCase()}${a.hasMask?' · 투명 마스크 합성':''}`;links+=downloadLink(a.preview,'호환 PNG');}if(a.assetType==='graphics'){details+=`\n원본 영역 [${a.bbox.join(', ')}] · 배경을 포함한 영역 추출. 원본의 블루 음영과 클리핑 외형을 보존합니다.`;links+=downloadLink(a.preview,'PNG');if(a.isolatedPath){links+=downloadLink(a.isolatedPath,'배경 분리 SVG');}if(a.isolatedPreview){links+=downloadLink(a.isolatedPreview,'투명 PNG · 근사 분리');details+='\n투명 PNG는 밝은 배경을 제거한 파생본입니다. 원본 보존용은 배경 포함 SVG/PNG를 사용하세요.';}if(a.limitations)details+='\n'+(Array.isArray(a.limitations)?a.limitations.join(' '):a.limitations);}if(a.origin==='extension'){details+='\n48 × 48 viewBox · 균일한 3-unit 선 · 둥근 끝과 모서리. 원본 추출물이 아닙니다.';if(a.gradientPath)links+=downloadLink(a.path,'인쇄용 단색 SVG');links+=`<button class="button primary" data-use-recipe="${escapeHTML(a.id)}">이 주제로 프롬프트 구성 ↗</button>`;}links+=`<button class="button secondary" data-page="${a.pages[0]}">참고 페이지 보기 ↗</button>`;showDialog({title:a.label,kind:a.origin==='extension'?'EXTENSION / OUTLINE':'ORIGINAL / SOURCE ASSET',image:a.preview,description:details,links,isIcon:a.assetType==='icons'},trigger);}
  function showPage(number,trigger){const p=source.pages.find(p=>p.number===number);if(!p)return;if($('asset-dialog').open)$('asset-dialog').close();showDialog({title:`${String(p.number).padStart(2,'0')} / ${p.title}`,kind:'SOURCE PAGE / 52',image:p.preview,description:`${pageNames[p.category]||p.category} · ${p.width} × ${p.height} PDF units\n이미지 ${p.imageIds.length}개 · 폰트 ${p.fontNames.map(x=>x.replace(/^[A-Z]+\+/, '')).join(', ')}\nSVG는 글자 윤곽선을 보존합니다. 문구·폰트·좌표는 텍스트 JSON에서 확인하세요.`,links:downloadLink(p.svg,'페이지 SVG')+downloadLink(p.preview,'미리보기 JPG')+downloadLink(p.text,'텍스트 JSON')+downloadLink(p.geometry,'도형 JSON')+`<a class="button primary" href="${pathURL(source.document.filename)}#page=${p.number}" target="_blank" rel="noopener">PDF에서 열기 ↗</a>`},trigger);}
  const templateNames={cover:'표지',contents:'목차',divider:'장 구분',statement:'핵심 메시지',metrics:'성과 · 지표',comparison:'비교 · 제안 범위',process:'프로세스', 'case-study':'프로젝트 사례',gallery:'이미지 갤러리',closing:'마무리 · 연락처'};
  function renderLayouts(){ $('layout-grid').innerHTML=system.templates.filter(t=>t.category==='slide').map(t=>`<article class="layout-card"><img class="layout-thumb" src="${pathURL(t.svg)}" alt="${escapeHTML(templateNames[t.id]||t.name)} 템플릿" loading="lazy"><div class="layout-info"><div class="layout-info-head"><h3>${escapeHTML(templateNames[t.id]||t.name)}</h3><span class="badge derived">재구성</span></div><p>${escapeHTML(t.description)}</p><div class="layout-info-foot"><span>16:9 · ${pageRefs(t.sourcePages)}</span><a class="text-link" href="${pathURL(t.svg)}" download>SVG 받기 ↓</a></div></div></article>`).join('');}
  function renderSources(){const q=$('source-search').value.trim().toLocaleLowerCase();const cat=$('source-category').value;const pages=source.pages.filter(p=>(cat==='all'||p.category===cat)&&[String(p.number).padStart(2,'0'),p.title,p.category,p.searchText||''].join(' ').toLocaleLowerCase().includes(q));$('source-count').textContent=`${pages.length} / ${source.pages.length} 페이지`;$('source-grid').innerHTML=pages.length?pages.map(p=>`<button class="source-card" data-page="${p.number}"><img src="${pathURL(p.preview)}" alt="${p.number}쪽 ${escapeHTML(p.title)}" loading="lazy" decoding="async"><span class="source-card-info"><span>${String(p.number).padStart(2,'0')}</span><span><h3>${escapeHTML(p.title)}</h3><small>${escapeHTML(pageNames[p.category]||p.category)} / SVG · TEXT · GEOMETRY</small></span></span></button>`).join(''):'<p class="empty-state">검색 결과가 없습니다. 검색어 또는 페이지 유형을 바꿔 주세요.</p>';}
  function composePrompt(){const family=$('prompt-family').value;const f=families[family];const subject=$('prompt-subject').value.trim();const context=$('prompt-context').value.trim();const format=$('prompt-output').value;const english=$('prompt-language').value==='en';const tone=$('prompt-tone')?.value||'gradient';$('prompt-tone').disabled=!['outline','solid'].includes(family);if(!subject){$('prompt-subject').setCustomValidity('새로운 주제를 입력해 주세요.');$('prompt-subject').reportValidity();return false;}$('prompt-subject').setCustomValidity('');
    const gradientStops=system.recipes[0]?.gradient?.stops||[{color:'#5C66D4'},{color:'#2733A1'},{color:'#051565'}];const gradientText=gradientStops.map(s=>s.color).join(' → ');
    const colorRule=family==='outline'||family==='solid'?(tone==='gradient'?`원본 SVG의 블루 그라데이션을 유지한다. 원본에서 평탄화된 블루 음영을 참고하며, 새 SVG에서는 샘플링 근삿값 ${gradientText}, 좌상단 → 우하단을 적용한다. 소재가 금괴여도 금색으로 바꾸지 않는다.`:'인쇄용 단색 확장: #091955 하나만 사용한다. SVG는 currentColor와 standalone fallback을 지원한다. 원본의 그라데이션을 생략한 파생 버전임을 명시한다.'):'계열별 색상 규칙과 참고 소스의 팔레트를 유지한다.';
    const englishColor=family==='outline'||family==='solid'?(tone==='gradient'?`Preserve the blue shading in the source SVG (its gradient may be flattened). For the new SVG use the sampled approximation ${gradientText}, top-left to bottom-right. Never recolor gold bars as gold material.`:'Print monochrome extension: #091955 only, SVG currentColor with standalone fallback. Label it a derived monochrome version of the original gradient artwork.'):'Preserve the family palette and the supplied reference colors.';
    const svgRule=family==='layout'?'독립형 1920×1080 SVG. 편집 가능한 텍스트, 의미 있는 그룹 ID. 이미지 자리는 교체 가능한 사각형으로 표시.':'유효한 독립형 SVG. viewBox와 title/desc, 의미 있는 그룹 ID를 포함. 스크립트, 외부 참조, base64 래스터, 외부 폰트 제외. 그라데이션은 필요 계열에서만 로컬 defs 사용.';
    const pngRule=['outline','solid','mascot'].includes(family)?'투명 PNG, 1024×1024, 중앙 정렬. 바둑판을 배경에 그리지 말 것. 작은 크기로 축소해도 선명하게.':'고해상도 PNG, 1920×1080. 해당 계열의 배경과 제목 안전 영역을 유지.';
    const references=f.pages.map(n=>`source/pages/page-${String(n).padStart(3,'0')}.svg`).join('\n');const g=graphicById(f.graphic);const attachment=g?`${g.path}\n${references}`:references;
    let text;
    if(english)text=`TASK\nCreate one ${f.english.toLowerCase()} for: ${subject}\n\nCONTEXT (user supplied)\n${context||'Proposal / business document'}\n\nREFERENCE FILES TO ATTACH\n${attachment}\nThese paths are local files: attach the actual files to your generation tool.\n\nFIXED STYLE\n${f.englishRules}\n${englishColor}\n\nALLOWED CHANGE\nChange the subject silhouette and only the details needed to convey its meaning. Match the reference optical weight, negative space and perspective. Mark the result as an extension, not extracted original artwork.\n\nOUTPUT\n${format==='svg'?`Valid standalone editable SVG; ${['outline','solid'].includes(family)?'48×48':family==='mascot'?'1024×1024':'1920×1080'} viewBox as appropriate to the reference. Include title/desc and grouped geometry. No scripts, external references, embedded rasters or remote fonts. Use local defs only for the chosen gradient family.`:`${['outline','solid','mascot'].includes(family)?'1024×1024 transparent PNG; centered; never draw a checkerboard background.':'1920×1080 PNG with the family background and title safe area.'}`}\n\nNEGATIVE PROMPT\n${f.englishNegative}\n\nQA\nCompare silhouette weight, line/fill treatment, gradient or palette, perspective, and margin against ${pageRefs(f.pages)}. For icons inspect at 24/48/96 px. If any trait changes, revise it. Clearly label sample figures; do not invent factual statistics.\n\nUSER SUBJECT IS QUOTED AS GIVEN; retain its intended meaning.`;
    else text=`[작업]\n${subject}를 ${f.name} 계열로 제작한다.\n\n[사용 맥락]\n${context||'제안서 및 기업 문서'}\n\n[첨부할 참고 소스]\n${attachment}\n위 경로는 로컬 파일이다. 생성 도구에 실제 파일을 함께 첨부한다.\n\n[고정할 스타일]\n${f.rules}\n${colorRule}\n\n[변경할 것]\n주제를 설명하는 실루엣과 최소한의 내부 단서만 변경한다. 같은 계열의 시각적 무게, 여백, 시점을 유지한다. 원본 추출물이 아닌 확장 결과물로 표시한다.\n\n[출력]\n${format==='svg'?svgRule:pngRule}\n\n[금지 사항 / NEGATIVE]\n${f.negative}\n\n[검수 기준]\n${pageRefs(f.pages)}와 나란히 비교해 선/면 처리, 색, 시점, 여백이 같은 계열인지 확인한다. 아이콘은 24/48/96px로 검수한다. 주제 인식에 필요하지 않은 디테일은 제거한다. 데이터 값은 임의로 사실처럼 만들지 않고, 예시이면 예시로 표시한다.`;
    $('prompt-result').value=text;$('prompt-family-badge').textContent=f.english;$('invariant-tags').innerHTML=f.tags.map(t=>`<span>${t}</span>`).join('');$('transformation-preview').hidden=family!=='outline';$('family-reference').hidden=family==='outline';$('family-reference').innerHTML=`<h3>${f.name}</h3><p>${f.description}</p><button class="link-button" data-page="${f.pages[0]}">원본 ${pageRefs(f.pages)} 확인 ↗</button>`;$('prompt-source-note').textContent=`${pageRefs(f.pages)} 참고 · 프롬프트 조합 결과 · 예시 이미지는 실시간 생성되지 않습니다.`;
    const house=system.recipes.find(r=>r.path.endsWith('/house.svg'));const gold=system.recipes.find(r=>r.path.endsWith('/gold-bars.svg'));if(house)$('example-house').src=tone==='gradient'?(house.gradientPath||house.path):house.path;if(gold)$('example-gold').src=tone==='gradient'?(gold.gradientPath||gold.path):gold.path;return true;
  }
  function useRecipe(id){const r=system.recipes.find(r=>r.id===id);if(!r)return;if($('asset-dialog').open)$('asset-dialog').close();$('prompt-family').value='outline';$('prompt-subject').value=r.name==='Gold Bars'?'금괴 3개가 쌓인 아이콘':`${r.name} / ${r.subject}`;$('prompt-context').value=r.description;composePrompt();location.hash='prompts';notify('선택한 주제를 프롬프트에 적용했습니다.');}
  function renderRecipes(){$('recipe-grid').innerHTML=system.recipes.map(r=>`<article class="recipe-card"><img src="${pathURL(r.gradientPath||r.path)}" alt="${escapeHTML(r.name)} 확장 아이콘" loading="lazy"><h3>${escapeHTML(r.name)}</h3><p>${escapeHTML(r.subject)}</p><div class="recipe-actions"><button class="link-button" data-use-recipe="${escapeHTML(r.id)}">프롬프트 적용 ↗</button><a class="text-link" href="${pathURL(r.gradientPath||r.path)}" download>SVG ↓</a></div></article>`).join('');}
  function renderDownloads(){const items=[['ZIP','원본 소스 아카이브','52쪽 SVG · 텍스트 · 도형 · 이미지 79개 · 폰트 서브셋','downloads/ark-source-archive.zip'],['PPTX','편집 가능한 PowerPoint','10개 슬라이드 · 텍스트와 도형 편집','templates/ark-proposal.pptx'],['ZIP','문서 템플릿 패키지','10개 SVG · PowerPoint · 편집 가능한 A4 HTML','downloads/ark-templates.zip'],['JSON','디자인 토큰','관찰값과 제안값, 출처를 포함한 색상 · 간격 · 타이포그래피','tokens.json'],['CSS','CSS 토큰','색상 · 간격 · 시스템 폰트 변수','tokens.css'],['ZIP','아이콘 & 프롬프트','계열별 가이드 · 16개 주제 SVG · 확장 레시피','downloads/ark-icon-kit.zip'],['MD','소스 분석과 디자인 규칙','원본의 시각적 특성 · 계열별 적용법 · 검수 기준','docs/visual-analysis.md'],['JSON','전체 추출 인벤토리','페이지·자산 경로, 출처, 서체, 색상, SHA-256','data/source-manifest.json'],['MD','사용 설명서','로컬 실행 · 파일 구성 · 추출 재현 · 검증 방법','README.md']];$('download-list').innerHTML=items.map(([ext,title,description,path])=>`<a class="download-item" href="${pathURL(path)}" download><span class="download-ext">${ext}</span><div><h3>${title}</h3><p>${description}</p></div><span>다운로드 ↓</span></a>`).join('');$('extraction-note').textContent=`${source.stats.pages||52}쪽 전체 SVG, ${source.stats.images||79}개 이미지, ${source.stats.fonts||16}개 폰트 서브셋, ${source.stats.drawings||1867}개 최상위 도형 레코드, ${source.stats.graphics||20}개 선별 그래픽을 보존했습니다. Form XObject 안의 추가 벡터는 페이지 SVG에 포함됩니다.`;}
  document.addEventListener('click',e=>{const link=e.target.closest('a[download]');if(link&&location.protocol==='file:'&&!link.href.startsWith('blob:')){link.target='_blank';link.rel='noopener';notify('파일이 새 탭에서 열리면 브라우저의 ‘다른 이름으로 저장’을 사용하세요.');}},true);
  document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){showPage(Number(page.dataset.page),page);return;}const asset=e.target.closest('[data-asset-id]');if(asset){showAsset(asset.dataset.assetId,asset);return;}const recipe=e.target.closest('[data-use-recipe]');if(recipe){useRecipe(recipe.dataset.useRecipe);return;}const family=e.target.closest('[data-use-family]');if(family){$('prompt-family').value=family.dataset.useFamily;composePrompt();location.hash='prompts';return;}});
  $('asset-filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;assetFilter=b.dataset.filter;assetLimit=32;document.querySelectorAll('[data-filter]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn===b)));renderAssets();});
  $('asset-search').addEventListener('input',()=>{assetLimit=32;renderAssets();});$('asset-more').addEventListener('click',()=>{assetLimit+=32;renderAssets();});$('asset-reset').addEventListener('click',()=>{$('asset-search').value='';document.querySelector('[data-filter="all"]').click();$('asset-search').focus();});
  $('source-search').addEventListener('input',renderSources);$('source-category').addEventListener('change',renderSources);
  $('dialog-close').addEventListener('click',()=>$('asset-dialog').close());$('asset-dialog').addEventListener('close',()=>{if(lastDialogTrigger?.isConnected)lastDialogTrigger.focus({preventScroll:true});});$('asset-dialog').addEventListener('click',e=>{if(e.target===$('asset-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  $('prompt-form').addEventListener('submit',e=>{e.preventDefault();if(composePrompt())notify('입력한 조건으로 프롬프트를 구성했습니다.');});$('prompt-form').addEventListener('change',composePrompt);$('prompt-subject').addEventListener('input',()=>{$('prompt-subject').setCustomValidity('');});document.querySelectorAll('[data-subject]').forEach(b=>b.addEventListener('click',()=>{$('prompt-subject').value=b.dataset.subject;composePrompt();}));
  $('prompt-copy').addEventListener('click',()=>{if(composePrompt())copyText($('prompt-result').value,$('prompt-result'));});$('prompt-download').addEventListener('click',()=>{if(composePrompt())downloadText($('prompt-result').value,'ark-creation-prompt.txt');});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&!$('asset-dialog').open){e.preventDefault();location.hash='assets';changeRoute();$('asset-search').focus();}});
  window.addEventListener('hashchange',changeRoute);
  if(!window.ARK_SOURCE||!window.ARK_SYSTEM){const b=document.createElement('p');b.className='error-banner';b.textContent='데이터 파일을 읽지 못했습니다. 압축을 완전히 해제한 뒤 index.html을 열거나 python3 scripts/build_system.py를 실행해 주세요.';$('main').prepend(b);}
  renderStats();renderColors();renderFamilies();renderAssets();renderLayouts();renderRecipes();renderSources();renderDownloads();composePrompt();changeRoute();
})();
