#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate index.html (the catalog) from tokens.json, source-coverage.json and references/assets-manifest.json."""
import json, pathlib, html
ROOT = pathlib.Path(__file__).resolve().parents[1]
tokens = json.loads((ROOT / 'tokens.json').read_text())
coverage = json.loads((ROOT / 'source-coverage.json').read_text())
manifest = json.loads((ROOT / 'references/assets-manifest.json').read_text())
E = html.escape
A = lambda name, kind='': next((a for a in manifest['assets'] if a['file'] and name in a['file']), {'file': ''})['file']
LOGO = A('logo-FINF'); ARROW = A('icon-7cES3'); CHECK = A('icon-c6ZeL'); STARS = A('icon-kgmUU')
FAN = [a['file'] for a in manifest['assets'] if a['role'] == 'nav-fan']
HERO_CIRCLE = A('hero-circle-Y1rp')
LIST_CHECK = A('icon-c6ZeL'); IC_DISCOVER = A('icon-WFCNF'); IC_DESIGN = A('icon-IgXeA'); IC_DELIVER = A('icon-Yoi0y'); CHEV = A('icon-7cES3')
FEATURED = A('photo-project-dUn1i'); ROW_THUMBS = [a['file'] for a in manifest['assets'] if a['role'] == 'photo-project' and 'dUn1i' not in a['file']]
SERVICE_THUMBS = [a['file'] for a in manifest['assets'] if a['role'] == 'photo-service']
AVATARS = [a['file'] for a in manifest['assets'] if a['role'] == 'photo-avatar']
BLOGS = [a['file'] for a in manifest['assets'] if a['role'] == 'photo-blog']
CLIENTS = [a['file'] for a in manifest['assets'] if a['role'] == 'client-logo']
PHOTO = {k: A(v) for k, v in {'project': 'photo-project-dUn1i', 'cta': 'photo-project-cta-3vlK', 'founder': 'photo-founder-WyGQ', 'service': 'photo-service-be9w', 'circle': 'hero-circle-Y1rp', 'avatar': 'photo-avatar-RaHJ', 'blog': 'photo-blog-rAhx'}.items()}
SOCIAL = [a['file'] for a in manifest['assets'] if a['role'] == 'icon-social' and any(k in a['file'] for k in ('X80b', 'M6jE', 's7rM', '7n5N'))]
CTA_STACK = [a['file'] for a in manifest['assets'] if a['role'] == 'photo-project-cta']

# ---- scene atlas
scenes = []
for i, s in enumerate(coverage['sections'], 1):
    frame = s['frame'].split(' / ')[0]
    scenes.append(f'<article class="scene-card"><a href="references/{E(frame)}" target="_blank"><div class="scene-image"><img src="references/{E(frame)}" alt="원본 캡처: {E(s["title"])}" loading="lazy"><span>y {s["y"]}px</span></div></a><div class="scene-copy"><span class="scene-number">{i:02d} / {E(s["group"].upper())}</span><h3>{E(s["title"])}</h3><p>{E(s["description"])}</p><a class="more" href="#{E(s["previewId"])}">대응하는 구현 보기 ↗</a></div></article>')

# ---- colors
sw = []
for name, c in tokens['color'].items():
    src = c.get('sourceVariable', '')
    sw.append(f'<button class="swatch" type="button" data-hex="{c["value"]}" title="{E(name)} 복사"><i style="background:{c["value"]}"></i><div><strong>{E(name)}</strong><code>{c["value"]}</code><small>{E(src[:16] + "…" if src else c["evidence"])}</small><small>{E(c["role"][:60])}</small></div></button>')

# ---- typography rows
def fmt(r, key='desktop'):
    d = r.get(key) or {}
    return f"{d.get('size','—')} / {d.get('lineHeight','—')}" if d else '—'
type_rows = []
spec = {'hero': ('bold', '64px', .8), 'sectionTitle': ('other projects', '50px', 1.1), 'statement': ('we don’t do fluff. just award-winning work.', '44px', 1.1), 'cardTitle': ('ready to grow your brand', '26px', 1.1), 'itemTitle': ('michael rey · brand strategy', '22px', 1.2), 'eyebrow': ('a note from the founder', '20px', 1.2), 'listTitle': ('the bold coach', '18px', 1.2), 'statNumber': ('100+ · 15+ · 95%', '34px', 1.1), 'statNumberLarge': ('5+', '50px', 1.1), 'navLabel': ('projects · about · services · contact', '18px', 1.2), 'body': ('we combine insight, strategy, and design to help you move forward confidently.', '16px', 1.2), 'bodyMedium': ('dear friends, at 3 circles we’ve always believed in building more than just websites.', '16px', 1.2), 'small': ('coaching, female entrepreneur · 2025', '14px', 1.2), 'smallStrong': ('discover · design · deliver', '14px', 1.2), 'micro': ('01 02 03 04', '10px', 1.1), 'button': ('book a 30-min call', '16px', 1.2)}
for key, r in tokens['typography']['roles'].items():
    text, size, lh = spec.get(key, (key, '16px', 1.2))
    color = 'var(--tc-flame)' if key == 'eyebrow' else 'inherit'
    fam = 'var(--tc-font-display)' if r['family'].startswith('Bricolage') else 'var(--tc-font-body)'
    tt = 'none' if r.get('textTransform') == 'none' else 'lowercase'
    type_rows.append(f'<div class="type-row"><div class="meta"><b>{E(key)}</b><span>{E(r["family"])} {r["weight"]}</span><span>1440 · {E(fmt(r))}</span><span>900 · {E(fmt(r,"tablet"))} · 390 · {E(fmt(r,"mobile"))}</span><span class="ev ev-live" style="justify-self:start">live</span></div><p class="specimen" style="font:{r["weight"]} {size}/{lh} {fam};color:{color};text-transform:{tt}">{E(text)}</p></div>')

# ---- assets
roles = ['all'] + sorted(manifest['roles'], key=lambda r: -manifest['roles'][r])
assets = []
for a in manifest['assets']:
    if not a['file']: continue
    photo = a['role'].startswith('photo') or a['role'] in ('hero-circle', 'nav-fan')
    assets.append(f'<a class="asset{" photo" if photo else ""}" data-role="{E(a["role"])}" href="{E(a["file"])}" target="_blank" title="{E(a["sourceUrl"])}"><div class="img"><img src="{E(a["file"])}" alt="{E(a["alt"] or a["role"])}" loading="lazy"></div><small>{E(a["role"])}</small><small>{E(a.get("note",""))}</small><small>{a["bytes"]:,} B</small></a>')
filters = ''.join(f'<button type="button" data-role="{r}" aria-pressed="{"true" if r=="all" else "false"}">{r} {len(manifest["assets"]) if r=="all" else sum(1 for a in manifest["assets"] if a["role"]==r)}</button>' for r in roles)

# ---- layout tables
L = tokens['layout']
sec_rows = ''.join(f'<tr><td><code>{E(k)}</code></td><td>{v["y"]}</td><td>{v["h"]}</td><td>{v["w"]}</td><td>{E(v["padding"])}</td><td>{L["tablet"]["sections"].get(k,{}).get("padding","—")}</td><td>{L["mobile"]["sections"].get(k,{}).get("padding","—")}</td></tr>' for k, v in L['desktop']['sections'].items())
grid_rows = ''.join(f'<tr><td><code>{E(k)}</code></td><td>{E(", ".join(f"{a} {b}" for a,b in v.items() if a!="evidence"))}</td></tr>' for k, v in L['grids'].items())
motion_rows = ''.join(f'<tr><td><code>{E(k)}</code></td><td>{E(v.get("trigger","—"))}</td><td>{E(v.get("change") or ", ".join(v.get("properties",[])))}</td><td>{E(str(v.get("duration") or v.get("transition") or "—"))} {E(v.get("easing",""))}</td><td>{E(v.get("evidence",""))}</td></tr>' for k, v in tokens['motion'].items())
comp_rows = ''.join(f'<tr><td><code>{E(k)}</code></td><td>{E("; ".join(f"{a}: {b}" for a,b in v.items() if a not in ("evidence","note")))}</td><td>{E(v.get("note",""))}</td></tr>' for k, v in tokens['components'].items())
clients_html = ''.join(f'<img src="{E(c)}" alt="">' for c in CLIENTS)

page = f'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>three circles — Design system extraction</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;500;600;700&family=Be+Vietnam+Pro:wght@400;500;600&family=Anonymous+Pro&display=swap"><link rel="stylesheet" href="studio-shell.css"><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="catalog.css"><link rel="stylesheet" href="studio-brand.css"></head>
<body><div class="as-studio"><a class="as-skip-link" href="#main">Skip to content</a>
<aside id="as-nav" class="as-sidebar" aria-label="Navigation"><a class="as-brand" href="#overview"><span class="as-brand-mark" aria-hidden="true"><i style="background:#67b935"></i><i style="background:#ffe479"></i><i style="background:#c5e7ff"></i></span><div><strong>three circles</strong><span class="small">Design system</span></div><span class="as-brand-badge">WEB</span></a><div class="as-sidebar-group"><span class="as-sidebar-label">WORKSPACE</span><div class="as-sidebar-caption">PROJECT SYSTEM / EDITION 01</div><nav aria-label="문서 목차"><a href="system.html"><span class="as-nav-index">01</span>프로젝트에 적용하기<span class="as-nav-count">1.0</span></a><a href="#overview"><span class="as-nav-index">02</span>overview</a><a href="#scene-atlas"><span class="as-nav-index">03</span>scene atlas<span class="as-nav-count">{len(scenes)}</span></a><a href="#motion"><span class="as-nav-index">04</span>motion playground<span class="as-nav-count">14</span></a><a href="#colors"><span class="as-nav-index">05</span>colors<span class="as-nav-count">{len(sw)}</span></a><a href="#type"><span class="as-nav-index">06</span>typography<span class="as-nav-count">{len(type_rows)}</span></a><a href="#layout"><span class="as-nav-index">07</span>layout &amp; shape</a><a href="#components"><span class="as-nav-index">08</span>components</a><a href="#assets"><span class="as-nav-index">09</span>assets<span class="as-nav-count">{len(assets)}</span></a><a href="#evidence"><span class="as-nav-index">10</span>sources</a><a href="#handoff"><span class="as-nav-index">11</span>handoff</a></nav></div><div class="as-sidebar-bottom"><span class="as-status-dot"></span><span> Captured 2026.09.14<small><a href="DESIGN.md">전체 명세 읽기 ↗</a> · <a href="tokens.json" download>JSON 다운로드 ↓</a></small></span><a href="https://three-circles-wbs.framer.website/" target="_blank" rel="noreferrer" aria-label="Open original website">↗</a></div></aside><button class="as-sidebar-scrim" aria-label="Close navigation" hidden></button>
<div class="as-main-shell"><header class="as-topbar"><button class="as-mobile-nav-button" aria-controls="as-nav" aria-expanded="false" aria-label="Open navigation">☰</button><div class="as-breadcrumb"><span>Design system</span><span>/</span><strong>Overview</strong></div><div class="as-topbar-tools"><button id="motion-toggle" class="as-motion-toggle tc-chip" type="button" aria-pressed="false">모션 줄이기</button><a class="as-export-button" href="tokens.json" download>Export tokens <span aria-hidden="true">↧</span></a></div></header>
<main id="main" tabindex="-1" class="as-workspace as-page-overview">
<section id="overview" class="intro"><header class="as-title-meta"><span>THREE CIRCLES / SYSTEM LIBRARY</span><span class="badge">SOURCE + RECONSTRUCTION</span></header><div class="as-eyebrow"><span class="as-status-dot"></span>bold. warm. hand-drawn.<span style="color:var(--tc-taupe)">2026.09</span></div><h1 class="tc-appear" id="overview-title">bold m<span class="tc-hero-mini" style="display:inline-flex;vertical-align:baseline;font-size:inherit"><span class="three" aria-hidden="true"><i></i><i></i><i></i></span></span>ves.<br>inspire gr<span class="o" style="display:inline-block;width:.55em;height:.55em;border-radius:50%;overflow:hidden;vertical-align:-.05em"><img src="{E(PHOTO['circle'])}" alt="" style="width:100%;height:100%;object-fit:cover"></span>wth.</h1><p class="lead">크림 종이 위 점선 카드, 한 가지 주황과 한 가지 노랑, 전부 소문자인 150px 제목.<br>three circles 원페이지 스튜디오 사이트의 시각 언어를 실측·토큰·동작하는 재구성으로 옮겼습니다.</p><div class="as-title-actions"><a class="as-button" href="system.html">프로젝트 적용 가이드 ↗</a><a class="as-text-command" href="#motion">모션 직접 조작 ↗</a></div><div class="as-stats-strip"><div><strong>14</strong><span>interactive reconstructions</span></div><div><strong>{len(scenes)}</strong><span>reference scenes</span></div><div><strong>{len(sw)}</strong><span>color tokens</span></div><div><strong>{len(assets)}</strong><span>source assets</span></div></div><div class="tag-row"><a href="three-circles-project-kit.zip" download>실무용 키트 ZIP ↓</a><a href="#scene-atlas">{len(scenes)} reference scenes ↗</a><a href="#colors">{len(sw)} color tokens ↗</a><a href="#type">{len(type_rows)} type roles ↗</a><a href="layout-recipes.html">5 layout recipes ↗</a></div><p class="note">서빙 HTML의 Framer 토큰과 1440/900/390px computed style, hover·sticky·appear 프로브를 바탕으로 재구성했습니다. Framer 변형의 시간 값처럼 측정하지 못한 수치는 카드마다 "제안"으로 표시합니다.</p></section>

<section id="scene-atlas"><div class="as-section-heading"><div><div class="as-eyebrow">03 / SCENE ATLAS</div><h2>every section, accounted for.</h2><p>1440px 원본 캡처 {len(scenes)}장. 각 장면의 실측 위치와 대응하는 재구성으로 바로 이동합니다.</p></div><span class="count-bubble">{len(scenes)}</span></div><div class="scene-grid">{''.join(scenes)}</div></section>

<section id="motion"><div class="as-section-heading"><div><div class="as-eyebrow">04 / MOTION PLAYGROUND</div><h2>not just a screenshot.</h2><p>마우스를 올리고, 누르고, 스크롤해 보세요. 2차 감사에서 nav 카드 확장은 hover가 아니라 스크롤 상태임을 확인해 수정했고, 티커 속도·이미지 fan·featured 확대·프로그레시브 블러·상태 펄스·모바일 메뉴를 추가했습니다.</p></div><span class="count-bubble">14</span></div><div class="evidence-key"><span><i class="ev ev-bundle">bundle</i> 페이지 데이터에서 확인</span><span><i class="ev ev-css">css</i> 선언값</span><span><i class="ev ev-probe">probe</i> hover/스크롤 측정</span><span><i class="ev ev-proposal">제안</i> 재구성 값</span><span>상단 "모션 줄이기"로 최종 상태를 확인하세요.</span></div><div class="motion-grid">
<article class="motion-card" id="appear-spring"><div class="motion-stage"><div class="tc-appear" id="appear-demo" style="text-align:center"><div class="tc-hero-mini" style="justify-content:center">b<span class="o"><img src="{E(HERO_CIRCLE)}" alt=""></span>ld</div><p style="font-size:13px;color:var(--tc-taupe);margin:10px 0 0">we combine insight, strategy, and design</p></div></div><div class="motion-body"><h3>hero appear <i class="ev ev-bundle">bundle</i></h3><p>로드 시 hero 왼쪽 블록이 30px 아래에서 올라오며 나타난다.</p><dl><dt>trigger</dt><dd>initial load</dd><dt>원본</dt><dd>spring stiffness 80 · damping 30 · mass 1 · delay .05s</dd><dt>재구성</dt><dd>translateY(30px) 1.2s ease-out (제안)</dd></dl><div class="motion-actions"><button type="button" data-replay="#appear-demo">다시 재생 ▶</button></div></div></article>
<article class="motion-card" id="reveal-button"><div class="motion-stage"><button class="tc-btn" id="reveal-demo" type="button">book a 30-min call</button></div><div class="motion-body"><h3>reveal button <i class="ev ev-probe">probe</i></h3><p>hover 시 왼쪽 위 모서리에서 노란 원이 8배(50→400px)로 커지며 채우고 글자가 ink로 바뀐다.</p><dl><dt>trigger</dt><dd>hover / focus</dd><dt>원본</dt><dd>Hover BG matrix(0) → matrix(8); color #FFF5D4 → #1C1B18</dd><dt>시간</dt><dd>미노출 → 450ms cubic-bezier(.44,0,.56,1) (제안)</dd></dl><div class="motion-actions"><button type="button" data-hover="#reveal-demo" aria-pressed="false">hover 고정</button></div></div></article>
<article class="motion-card" id="project-row"><div class="motion-stage" style="align-items:stretch;padding:20px"><div style="width:100%;align-self:center"><a class="tc-row" id="row-demo" href="#project-row"><b>art by liora</b><span class="thumb"><img src="{E(ROW_THUMBS[0])}" alt=""></span><span>portfolio website, artist</span><span>2024</span></a><a class="tc-row" href="#project-row"><b>alex rey creative</b><span class="thumb"><img src="{E(ROW_THUMBS[1])}" alt=""></span><span>designer portfolio</span><span>2023</span></a></div></div><div class="motion-body"><h3>project row <i class="ev ev-probe">probe</i></h3><p>행에 올리면 제목 옆 1px 슬롯이 90px로 열리며 썸네일이 드러나고, 메타 텍스트가 taupe에서 ink로 진해진다.</p><dl><dt>trigger</dt><dd>hover</dd><dt>원본</dt><dd>wrap 1 → 90px · title 464 → 365px · meta #675E50 → #1C1B18</dd><dt>시간</dt><dd>450ms (제안)</dd></dl><div class="motion-actions"><button type="button" data-hover="#row-demo" aria-pressed="false">hover 고정</button></div></div></article>
<article class="motion-card" id="image-stack"><div class="motion-stage"><div class="tc-stack" id="stack-demo" aria-hidden="true">{"".join(f'<i style="background:url({E(c)}) center/cover"></i>' for c in CTA_STACK[:3])}</div></div><div class="motion-body"><h3>image stack <i class="ev ev-probe">probe</i></h3><p>"other projects" CTA의 카드 3장. 양옆 카드가 ±12° 기울어 있다가 hover 시 곧게 정렬된다.</p><dl><dt>trigger</dt><dd>hover on CTA</dd><dt>원본</dt><dd>rotate(∓12°) 129×168 → rotate(0) 100×150</dd><dt>시간</dt><dd>450ms (제안)</dd></dl><div class="motion-actions"><button type="button" data-hover="#stack-demo" aria-pressed="false">hover 고정</button></div></div></article>
<article class="motion-card" id="nav-card"><div class="motion-stage" style="padding:12px"><div class="tc-scrollspy-stage"><div class="cards"><a class="tc-navcard" href="#nav-card"><span class="top">projects <span class="num">01</span></span><span class="body cols"><span><strong>showcase of innovation</strong><br><span class="muted">est.15 - 2025</span></span><span class="tc-fan" aria-hidden="true">{''.join(f'<img src="{E(f)}" alt="">' for f in FAN)}</span></span></a><a class="tc-navcard" href="#nav-card"><span class="top">about <span class="num">02</span></span><span class="body cols" style="grid-template-columns:auto 1fr"><span class="since"><b>since</b><span>2015</span></span><span class="list"><span><img src="{E(LIST_CHECK)}" alt="">creative approach</span><span><img src="{E(LIST_CHECK)}" alt="">clear strategy</span><span><img src="{E(LIST_CHECK)}" alt="">lasting impact</span></span></span></a><a class="tc-navcard" href="#nav-card"><span class="top">services <span class="num">03</span></span><span class="body"><span class="box">we craft solutions that work—clean, clear, and result-oriented.</span><span class="muted">path to success:</span><span class="path"><span><img class="ic" src="{E(IC_DISCOVER)}" alt="">discover</span><img class="chev" src="{E(CHEV)}" alt=""><span><img class="ic" src="{E(IC_DESIGN)}" alt="">design</span><img class="chev" src="{E(CHEV)}" alt=""><span><img class="ic" src="{E(IC_DELIVER)}" alt="">deliver</span></span></span></a><a class="tc-navcard soft" href="#nav-card"><span class="top">contact <span class="num">04</span></span><span class="body"><span style="display:flex;gap:8px;align-items:center"><span class="tc-pill"><img src="{E(LOGO)}" alt="" style="height:13px"></span><span class="muted">+</span><span class="tc-pill dark">you</span></span><strong>let’s talk</strong><span class="muted">let’s team up to build something remarkable</span></span></a></div><div class="scroller" tabindex="0" aria-label="스크롤해서 nav 카드 확장 확인"><section>projects</section><section>about</section><section>services</section><section>contact</section></div></div></div><div class="motion-body"><h3>nav card · scroll state <i class="ev ev-probe">probe</i></h3><p>카드는 <strong>보이는 섹션</strong>에 따라 확장된다(hover 아님). 오른쪽 상자를 스크롤하면 해당 카드가 42px에서 150/150/181/169px로 열리며 인포그래픽(연도 박스·체크 목록·경로·pill)이 나타난다.</p><dl><dt>trigger</dt><dd>scroll-spy · data-highlight=true</dd><dt>원본</dt><dd>42 → 150 · 150 · 181 · 169px, Bottom 88–119px</dd><dt>시간</dt><dd>미노출 → 450ms (제안)</dd></dl></div></article>
<article class="motion-card" id="nav-fan"><div class="motion-stage"><a class="tc-navcard is-open" id="fan-demo" href="#nav-fan" style="max-width:320px"><span class="top">projects <span class="num">01</span></span><span class="body cols"><span><strong>showcase of innovation</strong><br><span class="muted">est.15 - 2025</span></span><span style="display:grid;gap:8px;justify-items:end"><span class="tc-fan" aria-hidden="true">{''.join(f'<img src="{E(f)}" alt="">' for f in FAN)}</span><span style="font-size:14px">8+ design assets</span></span></span></a></div><div class="motion-body"><h3>nav card image fan <i class="ev ev-probe">probe</i></h3><p>projects 카드에 마우스를 올리면 썸네일 4장이 다시 펼쳐진다. 바깥 쌍은 ±30°에서 0°로, 안쪽 쌍은 0°에서 ±30°로.</p><dl><dt>trigger</dt><dd>hover (desktop)</dd><dt>원본</dt><dd>48–55px · radius 15% · rotate ±30° ↔ 0° · translateX ±30 → 0</dd><dt>시간</dt><dd>약 650ms spring (14 샘플)</dd></dl><div class="motion-actions"><button type="button" data-hover="#fan-demo" aria-pressed="false">hover 고정</button></div></div></article>
<article class="motion-card" id="featured-hover"><div class="motion-stage" style="padding:12px"><div class="tc-media" id="media-demo"><img class="bg" src="{E(FEATURED)}" alt=""><div class="tc-pblur" id="pblur-demo" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><span class="tc-chip accent label">featured project</span><div class="cap"><b>the bold coach</b><span>coaching, female entrepreneur</span><span>2025</span></div></div></div><div class="motion-body"><h3>featured card · progressive blur <i class="ev ev-live">live</i></h3><p>hover 시 이미지가 1.05배로 커지고 캡션이 taupe→ink. 하단 220px에는 8겹 backdrop blur(0.78→100px)가 12.5% 밴드 마스크로 쌓여 점점 흐려진다.</p><dl><dt>trigger</dt><dd>hover / 정적 블러</dd><dt>원본</dt><dd>scale 1→1.05 · 8 layers · mask 12.5% steps</dd><dt>시간</dt><dd>미노출 → 450ms (제안)</dd></dl><div class="motion-actions"><button type="button" data-hover="#media-demo" aria-pressed="false">hover 고정</button><button type="button" data-blur-toggle="#pblur-demo" aria-pressed="true">블러 끄기</button></div></div></article>
<article class="motion-card" id="status-pulse"><div class="motion-stage"><span class="tc-chip" style="font-size:16px;padding:4px 10px"><i class="tc-dot" style="width:14px;height:14px;margin-right:4px"></i>available for the project</span></div><div class="motion-body"><h3>status pulse <i class="ev ev-live">live</i></h3><p>가용 상태 점 주위로 초록 링 두 개(24·30px)가 퍼지며 사라진다.</p><dl><dt>trigger</dt><dd>지속</dd><dt>원본</dt><dd>opacity .5 → 0 · 2050ms linear() spring · infinite</dd></dl></div></article>
<article class="motion-card" id="mobile-menu"><div class="motion-stage" style="padding:12px"><div class="tc-phone-panel"><div class="row"><img src="{E(LOGO)}" alt="three circles" style="height:26px"><button class="tc-menu" type="button" aria-expanded="false" aria-controls="phone-menu-demo" aria-label="menu"><i></i><i></i></button></div><div class="grid" id="phone-menu-demo" hidden><a class="tc-navcard sm" href="#mobile-menu"><span class="top">projects <span class="num">01</span></span></a><a class="tc-navcard sm" href="#mobile-menu"><span class="top">about <span class="num">02</span></span></a><a class="tc-navcard sm" href="#mobile-menu"><span class="top">services <span class="num">03</span></span></a><a class="tc-navcard sm" href="#mobile-menu"><span class="top">contact <span class="num">04</span></span></a></div></div></div><div class="motion-body"><h3>mobile menu <i class="ev ev-probe">probe</i></h3><p>≤809px: 32px 크림 버튼의 두 줄이 X로 회전하고 ink 70% 스크림이 나타난다. 카드는 172×28 폰 변형(2px radius, 16/600, 20px 배지)으로 2열.</p><dl><dt>trigger</dt><dd>tap</dd><dt>원본</dt><dd>스크림 0→1 약 450ms · 줄 20×2 → 16px X(±45°)</dd></dl></div></article>
<article class="motion-card" id="ticker"><div class="motion-stage"><div class="tc-ticker" aria-label="client logos"><div class="track" aria-hidden="true">{clients_html}</div><div class="track" aria-hidden="true">{clients_html}</div></div></div><div class="motion-body"><h3>client ticker <i class="ev ev-probe">probe</i></h3><p>클라이언트 로고 14종이 vanilla 띠 안에서 흐른다. 마우스를 올리면 원본은 1/10 속도로 느려지고(재구성은 정지), 드래그 커서(ew-resize)를 보인다.</p><dl><dt>trigger</dt><dd>지속 재생 · hover · drag</dd><dt>원본</dt><dd>40px/s · hover 4px/s · gap 60 · 트랙 2,376px ≈ 59s/loop</dd><dt>재구성</dt><dd>59s linear infinite, hover 정지</dd></dl></div></article>
<article class="motion-card" id="sticky-title"><div class="motion-stage" style="padding:0"><div class="tc-sticky-box" tabindex="0" aria-label="스크롤해서 sticky 제목 확인"><div style="height:40px"></div><div class="sticky">hear from our<br>satisfied clients</div><div class="cards"><div style="top:-40px;left:12px">maya lin<br><small>founder, luna botanicals</small></div><div style="top:60px;right:12px">lena torres<br><small>manager</small></div><div style="top:200px;left:30px">drew kim<br><small>co-founder, loopwave</small></div><div style="top:320px;right:30px">michael rey<br><small>creative director</small></div></div></div></div><div class="motion-body"><h3>sticky title <i class="ev ev-probe">probe</i></h3><p>500px 제목이 화면 중간에 고정되고 후기 카드 4장이 그 위로 지나간다. 상자 안을 스크롤해 보세요.</p><dl><dt>trigger</dt><dd>scroll</dd><dt>원본</dt><dd>position: sticky · 제목 500px · 카드 420px vanilla</dd></dl></div></article>
<article class="motion-card" id="form-field"><div class="motion-stage"><p class="tc-sentence">my name is <input class="tc-field" aria-label="name" placeholder=""> , my email is <input class="tc-field" type="email" aria-label="email"></p></div><div class="motion-body"><h3>underline focus <i class="ev ev-css">css</i></h3><p>문장 사이의 점선 밑줄 입력. 포커스하면 밑줄이 stone에서 taupe로 진해진다.</p><dl><dt>trigger</dt><dd>focus</dd><dt>원본</dt><dd>border 0 0 1px dashed #B7B0A5 → #675E50</dd><dt>시간</dt><dd>all .45s cubic-bezier(.44,0,.56,1)</dd></dl></div></article>
<article class="motion-card" id="blog-card"><div class="motion-stage"><div class="blog-mini"><a class="tc-blogtitle" id="blog-demo" href="#blog-card">why your brand needs a story before a logo</a><hr><div style="display:flex;gap:10px;align-items:center;font-size:14px;color:var(--tc-taupe)"><span class="tc-chip">branding</span>nov 13, 2025</div></div></div><div class="motion-body"><h3>blog title hover <i class="ev ev-css">css</i></h3><p>카드 제목이 ink에서 flame으로 바뀐다. 사이트의 유일한 색 전환 hover다.</p><dl><dt>trigger</dt><dd>hover</dd><dt>원본</dt><dd>#1C1B18 → #F06231</dd><dt>시간</dt><dd>color .3s cubic-bezier(.44,0,.56,1)</dd></dl><div class="motion-actions"><button type="button" data-hover="#blog-demo" aria-pressed="false">hover 고정</button></div></div></article>
<article class="motion-card" id="reduced-motion"><div class="motion-stage"><div style="display:grid;gap:10px;justify-items:center"><button class="tc-btn accent" type="button">get started now</button><span class="tc-chip"><i class="tc-dot"></i>available for the project</span></div></div><div class="motion-body"><h3>reduced motion <i class="ev ev-proposal">제안</i></h3><p>모션 감소 설정에서는 티커·appear·reveal 확대를 멈추고 최종 상태만 보여준다. 상단 토글로 확인.</p><dl><dt>trigger</dt><dd>prefers-reduced-motion</dd><dt>적용</dt><dd>animation: none · transition: none</dd></dl></div></article>
</div></section>

<section id="colors"><div class="as-section-heading"><div><div class="as-eyebrow">05 / COLORS</div><h2>one orange, one yellow.</h2><p>Framer 토큰 16개(ID 보존)와 computed 값 2개. 클릭하면 hex를 복사합니다. 이름과 역할은 해석입니다.</p></div><span class="count-bubble">{len(sw)}</span></div><div class="swatch-grid">{''.join(sw)}</div><p class="caption" style="margin-top:14px">flame은 cream 위에서 3.1:1이라 24px 이상 제목·아이콘·표면에만 씁니다. stone 텍스트는 다크 표면에서만. 키트의 시맨틱 색상은 <code>design-system/tokens.json</code>에서 대비를 검증합니다.</p></section>

<section id="type"><div class="as-section-heading"><div><div class="as-eyebrow">06 / TYPOGRAPHY</div><h2>all lowercase, zero tracking.</h2><p>Bricolage Grotesque(제목·숫자)와 Be Vietnam Pro(본문·라벨·버튼). 거의 모든 스타일이 <code>text-transform: lowercase</code>, <code>letter-spacing: 0em</code>입니다. 1440 / 900 / 390px 실측.</p></div></div><div class="type-list">{''.join(type_rows)}</div></section>

<section id="layout"><div class="as-section-heading"><div><div class="as-eyebrow">07 / LAYOUT &amp; SHAPE</div><h2>400 + 980, dashed.</h2><p>sticky 사이드바 400px과 콘텐츠 980px. 그림자 없이 1px 점선과 6px/2px 라운드만 씁니다.</p></div></div><div class="grid-3" style="margin-bottom:20px"><div class="card"><h3>breakpoints</h3><p><code>{E(L['breakpoints']['desktop'])}</code> 사이드바 400 + 콘텐츠 980 + 여백 40<br><code>{E(L['breakpoints']['tablet'])}</code> 콘텐츠 580 단일 컬럼<br><code>{E(L['breakpoints']['mobile'])}</code> 콘텐츠 370, 상단 바 72px</p></div><div class="card"><h3>radius</h3><p>6px 카드·버튼·이미지·패널 (125개) · 2px 칩·라벨 (45개) · 50% 원 (14개) · 100px pill. 그 사이 값은 없습니다.</p></div><div class="card"><h3>border &amp; elevation</h3><p><code>1px dashed #B7B0A5</code> 상자 84개, 하단 구분선 27개. 그림자는 컴포넌트에 없음. 한 곳에서 <code>1px dashed #1C1B18</code>.</p></div></div><div class="card" style="margin-bottom:20px;overflow:auto"><h3>sections (1440px)</h3><table><thead><tr><th>id</th><th>y</th><th>height</th><th>width</th><th>padding 1440</th><th>900</th><th>390</th></tr></thead><tbody>{sec_rows}</tbody></table></div><div class="card" style="overflow:auto"><h3>grids</h3><table><tbody>{grid_rows}</tbody></table></div></section>

<section id="components"><div class="as-section-heading"><div><div class="as-eyebrow">08 / COMPONENTS</div><h2>cards, chips, rows.</h2><p>원본 computed 값으로 재구성한 정적 컴포넌트. 실무용 클래스는 <a href="system.html">프로젝트 적용 가이드</a>의 <code>.tcs-*</code>를 사용합니다.</p></div></div><div class="comp-grid">
<div class="comp-card"><h3>buttons <i class="ev ev-live">live</i></h3><div class="stage"><button class="tc-btn" type="button">book a 30-min call</button><button class="tc-btn accent" type="button">get started now</button><button class="tc-btn accent small" type="button">let’s talk</button></div><div class="stage" style="background:var(--tc-ink)"><button class="tc-btn submit" type="button">send a message</button><button class="tc-btn accent" type="button">book a call</button></div><p>ink/vanilla <code>16px 48px</code> 51px · butter <code>16px 48px</code> · small <code>15px 30px</code> 49px · submit <code>24px 74px</code> 67px. 모두 radius 6, Be Vietnam Pro 400 16px lowercase.</p></div>
<div class="comp-card"><h3>chips &amp; pills <i class="ev ev-live">live</i></h3><div class="stage"><span class="tc-chip"><i class="tc-dot"></i>available for the project</span><span class="tc-chip">est.2015</span><span class="tc-chip"><img src="{E(ARROW)}" alt="" style="height:12px"></span><span class="tc-chip accent">featured project</span><span class="tc-chip">branding</span><span class="tc-chip">market positioning</span><span class="tc-pill">+</span><span class="tc-pill dark">you</span></div><p>vanilla 2px <code>2px 6px</code> 14px · butter 강조 · flame/ink pill 100px <code>4px 12px</code> 25px.</p></div>
<div class="comp-card"><h3>sidebar &amp; nav cards <i class="ev ev-live">live</i></h3><div class="stage" style="background:var(--tc-flame);flex-direction:column;align-items:stretch;gap:8px"><div style="display:flex;gap:8px;margin-bottom:8px"><img src="{E(LOGO)}" alt="three circles logo" style="height:26px"></div><a class="tc-navcard" href="#components"><span class="top">projects <span class="num">01</span></span></a><a class="tc-navcard" href="#components"><span class="top">services <span class="num">03</span></span></a><div style="margin-top:12px;color:var(--tc-cream);font:500 22px/1.1 var(--tc-font-display)">reserve a time to speak with our experts</div><button class="tc-btn" type="button" style="align-self:flex-start">book a 30-min call</button><div style="background:var(--tc-cream);border-radius:6px;padding:14px 20px;display:flex;justify-content:space-between;align-items:center;font-size:14px">©2025 three circles.<span class="tc-social">{"".join(f'<a href="#components" aria-label="social"><img src="{E(s)}" alt=""></a>' for s in SOCIAL)}</span></div></div><p>flame 패널 360×960 padding 20 · 카드 320×42 <code>8px 16px</code> 라벨 18/600 · 번호 26px 흰 원 10/600 · 저작권 카드 cream padding 20.</p></div>
<div class="comp-card"><h3>service card <i class="ev ev-live">live</i></h3><div class="stage"><div class="service-mini"><div class="thumbs" aria-hidden="true">{"".join(f'<img src="{E(t)}" alt="">' for t in SERVICE_THUMBS[:3])}</div><h4>brand strategy</h4><div class="chips"><span class="tc-chip">market positioning</span><span class="tc-chip">audience research</span></div></div><div class="tc-dark" style="width:200px;min-height:240px;display:flex;flex-direction:column;gap:14px"><span style="display:flex;gap:6px"><i style="width:18px;height:18px;border-radius:50%;background:#67b935"></i><i style="width:18px;height:18px;border-radius:50%;background:#ffe479"></i><i style="width:18px;height:18px;border-radius:50%;background:#c5e7ff"></i></span><span style="font:500 22px/1.1 var(--tc-font-display)">ready to grow your brand</span><button class="tc-btn accent small" type="button" style="margin-top:auto;align-self:flex-start">let’s talk</button></div></div><p>313×300 점선 카드 padding 20 · 썸네일 70px 회전 스택 · 제목 22/500 · 하단 칩. 마지막 셀은 ink 카드.</p></div>
<div class="comp-card"><h3>stat &amp; rating <i class="ev ev-live">live</i></h3><div class="stage"><div class="stat-mini"><b>100+</b><span>a brand built from the ground up</span></div><div class="stat-mini vanilla"><b>95%</b><span>customer satisfaction score</span></div></div><div class="stage"><b style="font:700 50px/1.1 var(--tc-font-display)">4.5<small style="font-size:16px;font-weight:400">/5</small></b><div><img src="{E(STARS)}" alt="5 stars" style="height:18px;display:block"><small style="color:var(--tc-taupe);font-size:14px">trusted by clients</small></div></div><p>197×176 padding 20 · 숫자 34/500 · 평점 50/700 · 별 flame.</p></div>
<div class="comp-card"><h3>testimonial &amp; blog <i class="ev ev-live">live</i></h3><div class="stage"><div class="testi-mini"><div><b>maya lin</b><small>founder, luna botanicals</small></div><img src="{E(PHOTO['avatar'])}" alt=""><p>they understood our complex startup vision and brought it to life with clarity.</p></div><div class="blog-mini"><a class="tc-blogtitle" href="#components">2025 branding trends that actually matter</a><hr><div style="display:flex;gap:10px;align-items:center;font-size:14px;color:var(--tc-taupe)"><span class="tc-chip">ux design</span>nov 5, 2025</div><img src="{E(PHOTO['blog'])}" alt=""></div></div><p>후기 420px vanilla 점선 · 이름 22/500 · 이미지 100px. 블로그 313×318 padding 20 · 제목 22/500 · 점선 구분 · 이미지 6px.</p></div>
<div class="comp-card"><h3>sentence form <i class="ev ev-css">css</i></h3><div class="stage" style="background:#fff;border:var(--tc-dash);flex-direction:column;align-items:stretch"><div style="font:700 40px/1.1 var(--tc-font-display);text-align:center">drop us a note</div><p class="tc-sentence">my name is <input class="tc-field" aria-label="name"> , my email address is <input class="tc-field" type="email" aria-label="email"> , i am contacting you regarding <input class="tc-field" aria-label="subject" style="flex:1"></p><p class="tc-sentence">i want to tell you that:</p><textarea class="tc-field" aria-label="message" rows="3" style="width:100%"></textarea><button class="tc-btn submit" type="button" style="align-self:flex-start">send a message</button></div><p>흰 카드 padding 60 · 입력 16px 투명 · 밑줄 1px dashed stone → focus taupe · placeholder taupe · 제출 <code>24px 74px</code>.</p></div>
<div class="comp-card"><h3>footer <i class="ev ev-live">live</i></h3><div class="stage tc-dark" style="flex-direction:column;align-items:flex-start;gap:14px"><div style="font:700 40px/1.1 var(--tc-font-display)">it’s time<br>to level up<br>your brand</div><button class="tc-btn accent" type="button">book a call</button><div style="font-size:14px;color:var(--tc-stone)">join our creative circle</div><div style="display:flex;gap:8px;align-items:center"><input class="tc-footer-input" placeholder="enter email address" aria-label="email"><img src="{E(ARROW)}" alt="" style="height:12px;filter:invert(1)"></div><hr style="width:100%;border:0;border-top:1px dashed var(--tc-taupe);margin:6px 0"><div class="tc-social">{"".join(f'<a href="#components" aria-label="social"><img src="{E(s)}" alt="" style="filter:invert(1)"></a>' for s in SOCIAL)}</div><small style="color:var(--tc-stone);font-size:13px">designed by <a href="#components">webestica</a>, powered by <a href="#components">framer</a></small></div><p>ink 카드 980×425 <code>60px 60px 30px</code> · 제목 50/700 cream · butter CTA · 입력 white-10 + 1px taupe + 모노 placeholder stone · 점선 구분선 · 링크 hover flame · 소셜 opacity .7.</p></div>
</div><details style="margin-top:20px"><summary>컴포넌트 실측 표 전체 보기</summary><div class="card" style="margin-top:10px;overflow:auto"><table><thead><tr><th>component</th><th>values</th><th>note</th></tr></thead><tbody>{comp_rows}</tbody></table></div></details><details><summary>모션 실측 표 전체 보기</summary><div class="card" style="margin-top:10px;overflow:auto"><table><thead><tr><th>pattern</th><th>trigger</th><th>change</th><th>time / easing</th><th>evidence</th></tr></thead><tbody>{motion_rows}</tbody></table></div></details></section>

<section id="assets"><div class="as-section-heading"><div><div class="as-eyebrow">09 / ASSETS</div><h2>marks, icons, logos, photos.</h2><p>서빙 HTML과 렌더링 DOM이 참조하는 이미지 {len(assets)}개 전부를 역할·원본 URL·SHA-256과 함께 보관했습니다(래스터는 width=1400). 문서용 참조이며 사용 권한을 이전하지 않습니다.</p></div><span class="count-bubble">{len(assets)}</span></div><div class="asset-filter" role="group" aria-label="에셋 분류">{filters}</div><div class="asset-grid">{''.join(assets)}</div><p class="caption" style="margin-top:14px">폰트: {E('; '.join(f"{f['family']} ({f['weights']})" for f in manifest['fonts']))}.</p></section>

<section id="evidence"><div class="as-section-heading"><div><div class="as-eyebrow">10 / SOURCES</div><h2>where every number comes from.</h2></div></div><div class="grid-3"><div class="card"><h3>captures</h3><p><a href="references/live-desktop.png">desktop 1440×8734</a> · <a href="references/live-tablet.png">tablet 900×7884</a> · <a href="references/live-mobile.png">mobile 390×9382</a> · <a href="references/live-desktop-scrolled.png">scrolled</a> · section-*.png {len(scenes)}장</p></div><div class="card"><h3>computed data</h3><p><a href="references/live-desktop.json">live-desktop.json</a> · <a href="references/live-tablet.json">tablet</a> · <a href="references/live-mobile.json">mobile</a> · <a href="references/live-components.json">components</a> · <a href="references/live-boxes.json">boxes</a> · <a href="references/live-details.json">details</a></p></div><div class="card"><h3>source &amp; reports</h3><p><a href="references/live-source.html">live-source.html</a> · <a href="references/live-report.md">live-report.md</a> · <a href="references/live-style-excerpts.md">style excerpts</a> · <a href="references/assets-manifest.json">assets-manifest.json</a> · <a href="tokens.json">tokens.json</a></p></div></div><div class="card" style="margin-top:20px"><h3>evidence grades</h3><table><thead><tr><th>grade</th><th>meaning</th><th>limit</th></tr></thead><tbody><tr><td><i class="ev ev-css">css</i></td><td>서빙 HTML의 토큰·인라인 변수</td><td>선언값 정확</td></tr><tr><td><i class="ev ev-live">live</i></td><td>렌더링 DOM / computed / 스크린샷</td><td>기록한 뷰포트에 한정</td></tr><tr><td><i class="ev ev-probe">probe</i></td><td>hover·스크롤·리로드 후 측정</td><td>Framer 변형 미발화 항목은 미확정</td></tr><tr><td><i class="ev ev-bundle">bundle</i></td><td>페이지의 appear/breakpoint 데이터</td><td>수치 정확</td></tr><tr><td><i class="ev ev-proposal">제안</i></td><td>재구성 값·보완 규칙</td><td>원본 구현 아님</td></tr></tbody></table></div></section>

<section id="handoff"><div class="as-section-heading"><div><div class="as-eyebrow">11 / HANDOFF</div><h2>take it to a project.</h2></div></div><div class="grid-3"><div class="card vanilla"><h3>1 · kit</h3><p><a href="three-circles-project-kit.zip" download>three-circles-project-kit.zip</a>의 <code>design-system/</code>을 복사하거나 <a href="three-circles-system-1.0.0.tgz" download>npm tarball</a>을 설치합니다.</p></div><div class="card vanilla"><h3>2 · guide</h3><p><a href="system.html">system.html</a>에서 라이트/다크·탭·대화상자·문장형 폼을 확인하고 <a href="design-system/README.md">README</a>의 클래스 규약을 따릅니다.</p></div><div class="card vanilla"><h3>3 · recipes</h3><p><a href="layout-recipes.html">layout-recipes.html</a>의 사이드바 셸·hero·프로젝트 리스트·서비스 그리드·후기 클러스터를 반응형으로 가져갑니다.</p></div></div><pre style="margin-top:20px">npm install ./three-circles-system-1.0.0.tgz
import '@three-circles/system/styles.css';
import {{ initThreeCirclesSystem }} from '@three-circles/system';
const ui = initThreeCirclesSystem(document.querySelector('#app'));</pre><p class="caption" style="margin-top:14px">전체 명세는 <a href="DESIGN.md">DESIGN.md</a>, 재생성·검증 명령은 <a href="README.md">README.md</a>에 있습니다.</p></section>
</main><div class="as-toast" role="status" aria-live="polite"></div></div></div>
<script src="studio-shell.js"></script><script src="catalog.js"></script>
</body></html>
'''
(ROOT / 'index.html').write_text(page, encoding='utf-8')
print('index.html', len(page), 'bytes;', len(scenes), 'scenes,', len(sw), 'swatches,', len(type_rows), 'type rows,', len(assets), 'assets')
