"""Generate scoped CSS from the evidence-annotated token registry."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'tokens.json').read_text())
css = ['/* Generated by tools/build-tokens.py. See tokens.json for evidence. */', '.ods {']
for name, token in data['tokens'].items():
    css.append(f'  --ods-{name}: {token["value"]};')
css += ['}', '@media (min-width: 810px) and (max-width: 1199.98px) {', '  .ods { --ods-display-size: 106px; --ods-heading-size: 50px; }', '}', '@media (max-width: 809.98px) {', '  .ods { --ods-display-size: 70px; --ods-heading-size: 40px; --ods-page-gutter: 20px; --ods-section-space: 80px; }', '}']
(root / 'tokens.css').write_text('\n'.join(css) + '\n')
