const toast=document.querySelector('#toast');let toastTimer;
function notify(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2400)}
for(const button of document.querySelectorAll('[data-copy]'))button.addEventListener('click',async()=>{try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(button.dataset.copy);else{const field=document.createElement('textarea');field.value=button.dataset.copy;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const copied=document.execCommand('copy');field.remove();button.focus();if(!copied)throw Error('copy')}notify(`${button.dataset.copy} 복사했습니다`)}catch{notify(`색상 값: ${button.dataset.copy}`)}});
const referenceVideo=document.querySelector('#reference-video');for(const button of document.querySelectorAll('[data-seek]'))button.addEventListener('click',()=>{referenceVideo.currentTime=Number(button.dataset.seek);notify(`${button.textContent} 구간으로 이동했습니다`)});
for(const button of document.querySelectorAll('[data-demo-message]'))button.addEventListener('click',()=>notify(button.dataset.demoMessage));
const trigger=document.querySelector('#dropdown-button'),panel=document.querySelector('#dropdown-panel'),dropdown=trigger.closest('.dropdown');
function setDropdown(open){trigger.setAttribute('aria-expanded',String(open));panel.hidden=!open}
trigger.addEventListener('click',()=>setDropdown(trigger.getAttribute('aria-expanded')!=='true'));
dropdown.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse')setDropdown(true)});dropdown.addEventListener('pointerleave',()=>{if(!dropdown.contains(document.activeElement))setDropdown(false)});
dropdown.addEventListener('focusout',event=>{if(!dropdown.contains(event.relatedTarget))setDropdown(false)});
document.addEventListener('click',event=>{if(!dropdown.contains(event.target))setDropdown(false)});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!panel.hidden){setDropdown(false);trigger.focus()}});
const form=document.querySelector('#waitlist'),email=document.querySelector('#email'),message=document.querySelector('#form-message');form.addEventListener('submit',event=>{event.preventDefault();if(!email.validity.valid){email.setAttribute('aria-invalid','true');message.textContent='올바른 이메일 주소를 입력해 주세요.';email.focus();return}email.removeAttribute('aria-invalid');message.textContent='완료 상태 미리보기입니다. 이메일은 저장하거나 전송하지 않았습니다.';notify('폼 완료 상태를 표시했습니다')});email.addEventListener('input',()=>{email.removeAttribute('aria-invalid')});
const motionToggle=document.querySelector('#motion-toggle');const mediaQuery=window.matchMedia('(prefers-reduced-motion: reduce)');
function setReduced(value){document.documentElement.classList.toggle('reduce-motion',value);motionToggle.setAttribute('aria-pressed',String(value));motionToggle.textContent=value?'모션 줄임 · 켜짐':'모션 줄이기';if(value)referenceVideo.pause()}
setReduced(mediaQuery.matches);mediaQuery.addEventListener('change',event=>setReduced(event.matches));motionToggle.addEventListener('click',()=>{setReduced(motionToggle.getAttribute('aria-pressed')!=='true');if(mediaQuery.matches)notify('시스템 모션 감소 설정이 우선 적용됩니다')});document.querySelector('#replay')?.addEventListener('click',event=>{event.currentTarget.classList.toggle('shifted')});
const sectionLinks=[...document.querySelectorAll('.sidebar nav a')];const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){sectionLinks.forEach(link=>{const active=link.hash==='#'+entry.target.id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')})}},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('main>section').forEach(section=>observer.observe(section));
