#!/usr/bin/env python3
"""Build source-anchored motion specifications; offsets are UTF-8 decoded characters."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def ref(glob,needle,selector):
 p=next((ROOT/'source/js').glob(glob));s=p.read_text(); offset=s.index(needle)
 return {'file':str(p.relative_to(ROOT)),'offset':offset,'offsetUnit':'unicode-character','selector':selector,'excerpt':s[max(0,offset-80):offset+600]}
rows=[]
def add(id,title,category,trigger,values,description,glob,needle,selector,limits='Native WAAPI/CSS playback reconstruction; Framer runtime is not embedded.'):
 rows.append(dict(id=id,title=title,category=category,trigger=trigger,source='원본 수치 · 네이티브 재구성',evidenceLevel='source-extracted',values=values,descriptionKo=description,provenance=ref(glob,needle,selector),limitations=limits,code=json.dumps(values,ensure_ascii=False,indent=2)))
add('hero-characters','Character blur reveal','입장','replay / viewport',{'filter':['blur(10px)','blur(0px)'],'opacity':[.001,1],'y':[10,0],'startDelay':.1,'tokenization':'character','transition':{'bounce':0,'delay':.05,'duration':.4,'type':'spring'}},'문자별 10px 블러와 10px 이동. 0.1초 후 시작하며 문자 간 0.05초 간격을 재현합니다.','56d9*','Rt={effect:','.framer-24k4v','Source duration/bounce spring is approximated by cubic-bezier(.2,.8,.2,1); character delay interpretation is reconstructed.')
add('section-reveal','Section spring reveal','입장','replay / viewport',{'opacity':[0,1],'y':[150,0],'transition':{'damping':100,'delay':0,'mass':1,'stiffness':400,'type':'spring'}},'150px 아래에서 섹션이 부드럽게 정착합니다. 감쇠 100의 과감쇠 spring을 실제 방정식으로 샘플링합니다.','56d9*','W={opacity:0','.framer-24k4v')
add('card-stagger','Project card stagger','입장','replay / viewport',{'y':[150,0],'opacity':[0,1],'delays':[0,.2,.4,.6],'transition':{'damping':100,'mass':1,'stiffness':400}},'프로젝트 등장 프리셋에 기록된 0 / 0.2 / 0.4 / 0.6초 지연을 나란히 비교합니다.','56d9*','Ut={damping:100','.framer-24k4v')
add('hero-sequence','Hero opacity sequence','입장','replay / viewport',{'opacity':[.001,1],'delays':[.3,1.2,1.5],'transition':{'damping':66,'mass':1,'stiffness':400}},'히어로의 3개 opacity 프리셋을 원본 시간차로 재생합니다. 아래 텍스트 배치는 설명용입니다.','56d9*','It={opacity:1','.framer-24k4v')
add('rolling-link','Rolling navigation label','호버','hover / focus / replay',{'height':20,'gap':5,'transition':{'bounce':.2,'duration':.4,'type':'spring'}},'20px 텍스트 마스크와 5px 간격의 두 라벨을 이용한 수직 롤링 링크입니다.','1b74*','.framer-GL2RT .framer-ulnch2','.framer-GL2RT .framer-ulnch2','25px label translation reconstructed from 20px mask + 5px gap; timing is duration-spring approximation.')
add('primary-cta','View All Blogs / source CTA','호버','hover / focus / click / replay',{'label':'View All Blogs','href':'/blog','height':46,'padding':[4,56,4,20],'radius':50,'background':['#ff5d17','#0a0a0a'],'font':{'family':'Inter Tight','size':16,'weight':600,'lineHeight':1.2},'textRoll':False,'pressedScale':None,'circle':{'size':38,'inset':4,'radius':35,'color':'#ffffff'},'arrow':{'viewport':22,'iconSize':20,'gap':10,'viewportRotate':-45,'incomingX':[-28,0],'outgoingX':[2,30],'incomingIcon':['CaretRight','ArrowRight']},'transition':{'bounce':.2,'delay':0,'duration':.4,'type':'spring'}},'View All Blogs 원본 Primary CTA. 주황 → 검정, 고정된 -45° 마스크 안에서 두 화살표가 30px 교차합니다. 텍스트는 고정되며 원본에 눌림 축소 효과는 없습니다. 클릭하면 /blog 목적지를 표시합니다.','1b74*','.framer-GL2RT.framer-v-1tenthq.hover .framer-wizsgb','.framer-GL2RT.framer-v-1tenthq','Exact authored geometry, states and native link semantics. CSS .4s cubic-bezier(.2,.8,.2,1) approximates the source duration/bounce spring; SVG bold icon paths reconstructed. Keyboard focus maps to hover as an accessibility addition. Standalone reusable source: design-system/components/blog-cta.html/css/js. Primary text does not roll; only plain white/colored variants do.')
add('service-arrow','Service row arrow','호버','hover / focus / replay',{'rotate':[0,-45],'background':['#ffffff','#ff5d17'],'transition':{'damping':65,'mass':1,'stiffness':400}},'서비스 행 화살표가 -45도 회전하고 원형 배경이 주황색으로 바뀝니다.','b04a*','rotate:-45','.framer-DphBJ')
add('image-hover','Editorial image zoom','호버','hover / focus / replay',{'imageHeightRatio':[1.3107,1.5643],'scaleRatio':1.5643/1.3107,'cursorSize':[40,70],'cursorOpacity':[0,1],'transition':{'damping':60,'mass':1,'stiffness':400}},'원본 이미지 비율 1.3107 → 1.5643과 중앙 View 배지 40 → 70px를 함께 재현합니다.','340e*','1.5643','.framer-1gr6r5r','Image ratio and badge geometry source-extracted; authored spring 60/400/1 is approximated by 0.4s CSS. Badge is centered, not pointer tracking.')
add('logo-ticker','Logo ticker / 100px·s⁻¹','루프','visible autoplay / replay',{'speed':100,'direction':'left','gap':70,'hoverFactor':1,'fadeWidth':25,'fadeContent':True},'로고 트랙은 초당 100px로 이동합니다. 원본 hoverFactor 1이므로 호버해도 감속하지 않습니다.','56d9*','hoverFactor:1,id:`AanFXDgXw`','.framer-24k4v [data-framer-name="Ticker"]')
add('testimonial-ticker','Testimonial hover slowdown','루프','visible autoplay / hover / replay',{'speed':50,'direction':'left','gap':26,'hoverFactor':.01,'fadeContent':False},'Home v2 후기 트랙. 평상시 50px/s, 호버·키보드 포커스 시 0.5px/s로 감속합니다.','1a47*','hoverFactor:.01','.framer-1g3aje4 sibling ticker','Component is from Home v2; preview text and card dimensions are illustrative.')
add('faq','Independent FAQ expansion','상태','click / keyboard / replay',{'transition':{'damping':40,'mass':1,'stiffness':400},'lineRotate':[180,90],'answerOpacity':.62,'multiOpen':True},'항목별 독립 상태로 여러 답변을 동시에 열 수 있습니다. 두 선이 180° / 90° 회전해 +가 −로 바뀝니다.','9de4*','U={damping:40','.framer-3uLIP')
add('mobile-menu','Mobile menu expansion','상태','click / keyboard / replay',{'variants':['Mobile closed','Mobile open'],'transition':{'bounce':.2,'duration':.4,'type':'spring'},'entry':{'damping':65,'delay':.2,'mass':1,'stiffness':400}},'원본 모바일 열림/닫힘 variant를 로컬 패널로 재구성했습니다. 실제 사이트 이동 없이 메뉴 상태를 확인합니다.','d46c*','Xn={bounce:.2','.framer-JI5CD','Compact preview panel dimensions reconstructed; original desktop/mobile responsive geometry lives in source CSS.')
add('form-state','Form loading / success','상태','click / replay',{'variants':['Default','Loading','Disabled','Success','Error'],'transition':{'duration':.2,'ease':[.44,0,.56,1],'type':'tween'},'spinner':{'duration':1,'rotate':360,'ease':[0,0,1,1]}},'원본 Form 버튼의 loading / success / error 스타일과 1초 선형 spinner. 클릭하면 상태를 순서대로 비교합니다.','dbe0*','duration:.2,ease:[.44,0,.56,1]','.framer-tUylZ','Local state stepping only; no server request or simulated network success.')
add('slideshow-press','Slideshow arrow press','상태','pointer / keyboard / replay',{'whileTap':{'scale':.9},'transition':{'duration':.15}},'원본 슬라이드 이전/다음 버튼의 눌림 0.9배 피드백입니다. 이미지는 설명용 로컬 프레임입니다.','d46c*','whileTap:{scale:.9}','.framer--slideshow-controls button','Slide content swap is illustrative; no claim that original slide transition is 150ms.')
(ROOT/'motion-data.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
(ROOT/'motion-source-tokens.json').write_text(json.dumps({'schemaVersion':1,'source':'https://opalhaus.framer.website/','offsetUnit':'unicode-character','method':'Exact string anchors in archived authored modules; runtime-only values never promoted to authored tokens.','records':[{k:r[k] for k in ['id','values','provenance','limitations']} for r in rows]},ensure_ascii=False,indent=2)+'\n')
print(f'{len(rows)} motion records generated; all source anchors resolved')

# Keep the library self-contained for file:// use; metadata remains separately inspectable.
manifest=json.loads((ROOT/'assets/manifest.json').read_text())
image=next((f['path'] for f in manifest['files'] if 'VtQnwCyA4NkRzraLUljhLdqls' in f['url'] and f['path'].startswith('assets/')), '')
library=ROOT/'motion-library.js'
if library.exists():
 import re
 text=library.read_text()
 block='  /* MOTION_DATA_START */\n  const embeddedData = '+json.dumps(rows,ensure_ascii=False)+';\n  const embeddedImage = '+json.dumps(image)+';\n  /* MOTION_DATA_END */'
 text=re.sub(r'  /\* MOTION_DATA_START \*/.*?  /\* MOTION_DATA_END \*/',lambda m:block,text,flags=re.S)
 library.write_text(text)
